[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = true

[[hooks]]
stage = "build"
command = "tailwindcss"
command_arguments = ["-i", "styles.css", "-o", "dist/styles.css"]